id: P000236
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 25/11/2021
source_metadata:
  title: ༄༅། །རྒྱལ་བའི་དབང་པོ་ཀརྨ་པ་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེའི་གདམས་ཁྲིད་མན་ངག་གི་རིམ་པ་འཆི་མེད་བདུད་རྩིའི་ལྗོན་བཟང་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ༧ཀརྨ་མི་བསྐྱོད་རྡོ་རྗེ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
  - yigchung
  id: VVI-MD-001-1
web_metadata:
  title:
    en: A Magic Tree of Immortal Nectar:The Hundred Pith Instructions of Karmapa Mikyö
      Dorje, Volume 1
    bo: གདམས་ཁྲིད་མན་ངག་གི་རིམ་པ་འཆི་མེད་བདུད་རྩིའི་ལྗོན་བཟང་།
  collection:
    en: VVI Mikyo Dorje Series–  Book 1-1
    bo: མི་བསྐྱོད་རྡོ་རྗེ་གསུང་།–  དེབ། ༡-༡
  author:
    en: Eighth Karmapa Mikyo Dorje
    bo: ཀརྨ་པ་སྐུ་ཕྲེང་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེ།
  pusblisher:
    en: Vajra Vidya Institute
    bo: བཛྲ་བིདྱཱ་གཙུག་ལག་སློབ་གཉེར་ཁང་།
  sku: VVI-MD-001-1
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: VVI-MD-001-1.epub
  description:
    en: ༄༅། །དེང་འདིར་གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་ལམ་དང་། རིགས་འཛིན་གྲུབ་ཐོབ་རྒྱ་མཚོའི་ཤེགས་ཤུལ།
      ཚེ་ལུས་གཅིག་གིས་ཟུང་འཇུག་རྡོ་རྗེ་འཆང་གི་གོ་འཕང་མངོན་དུ་བྱེད་པའི་མན་ངག རྩ་གསུམ་རབ་འབྱམས་རྒྱལ་བའི་སྙིང་བཅུད་དྭངས་མའི་དྭངས་མ་ནི་ཕྱག་རྒྱ་ཆེན་པོ་ཞེས་པའི་སྒྲ་བོ་ཆེ་གཡེར་པོ་ཆེ་དེ་འཕགས་བོད་མཁས་གྲུབ་ཡོངས་ལ་རྩོད་མེད་དུ་གྲགས་པའི་བྱིན་རླབས་ཀྱི་རྒྱུན་ཉམས་པ་མེད་པའི་དངོས་གྲུབ་རྗེན་གཅེར་དུ་སྦྱིན་པའི་ཐབས་དང་ཐུགས་རྗེ་ཕུལ་དུ་བྱུང་བའི་རང་བཞིན་ཅན་གྱི་ཁྲིད་ཐུང་མར་གྲགས་པ་སངས་རྒྱས་ཀརྨ་པ་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེས་ཁ་སྦྱོར་བདུན་ལྡན་གྱི་དབང་ཕྱུག་དང་རོ་གཅིག་པའི་དབྱིངས་ནས་གདུལ་བྱ་ལ་ཆེད་དུ་བསྒྲགས་པའི་རིམ་པ་རྣམས་ཕྱོགས་གཅིག་བསྒྲིགས་པའི་ལེགས་བྱས་སུ་ཞུགས་པར་བྱ་བའང་བློ་ལྡོག་རྣམ་བཞི་ནས་བརྩམས་ཏེ་སྡེ་ཚན་རྣམས་རིམ་ལྡན་དུ་འབྱུང་བ་ཐོག་མ་ནས་ཤེས་པར་བྱ་དགོས་པའི་གནས་སོ།
      །
    bo: ༄༅། །དེང་འདིར་གསང་སྔགས་རྡོ་རྗེ་ཐེག་པའི་ལམ་དང་། རིགས་འཛིན་གྲུབ་ཐོབ་རྒྱ་མཚོའི་ཤེགས་ཤུལ།
      ཚེ་ལུས་གཅིག་གིས་ཟུང་འཇུག་རྡོ་རྗེ་འཆང་གི་གོ་འཕང་མངོན་དུ་བྱེད་པའི་མན་ངག རྩ་གསུམ་རབ་འབྱམས་རྒྱལ་བའི་སྙིང་བཅུད་དྭངས་མའི་དྭངས་མ་ནི་ཕྱག་རྒྱ་ཆེན་པོ་ཞེས་པའི་སྒྲ་བོ་ཆེ་གཡེར་པོ་ཆེ་དེ་འཕགས་བོད་མཁས་གྲུབ་ཡོངས་ལ་རྩོད་མེད་དུ་གྲགས་པའི་བྱིན་རླབས་ཀྱི་རྒྱུན་ཉམས་པ་མེད་པའི་དངོས་གྲུབ་རྗེན་གཅེར་དུ་སྦྱིན་པའི་ཐབས་དང་ཐུགས་རྗེ་ཕུལ་དུ་བྱུང་བའི་རང་བཞིན་ཅན་གྱི་ཁྲིད་ཐུང་མར་གྲགས་པ་སངས་རྒྱས་ཀརྨ་པ་བརྒྱད་པ་མི་བསྐྱོད་རྡོ་རྗེས་ཁ་སྦྱོར་བདུན་ལྡན་གྱི་དབང་ཕྱུག་དང་རོ་གཅིག་པའི་དབྱིངས་ནས་གདུལ་བྱ་ལ་ཆེད་དུ་བསྒྲགས་པའི་རིམ་པ་རྣམས་ཕྱོགས་གཅིག་བསྒྲིགས་པའི་ལེགས་བྱས་སུ་ཞུགས་པར་བྱ་བའང་བློ་ལྡོག་རྣམ་བཞི་ནས་བརྩམས་ཏེ་སྡེ་ཚན་རྣམས་རིམ་ལྡན་དུ་འབྱུང་བ་ཐོག་མ་ནས་ཤེས་པར་བྱ་དགོས་པའི་གནས་སོ།
      །
